Description of Subject
Subject
PURPOSE
Data representation of all informations related to one subject
SYNOPSIS
This is a script file.
DESCRIPTION
 Data representation of all informations related to one subject
   Contains:
           a name,
           edaValues,
           hrvValues,
           eegValuesForElectrodes,
           validElectrodes,
           isValid,
           edaPerVid,
   hence, two different constructors are necessary
   See: SubjectFactory, DataFactory
 Author: Gernot Heisenberg
CROSS-REFERENCE INFORMATION
This function calls:
Subject Data representation of all informations related to one subject
This function is called by:
Plotter Performs different plots
Subject Data representation of all informations related to one subject
SubjectFactory Factory class creating Subjects objects
SUBFUNCTIONS
function eegValues = eegValuesByElectrode(self, electrode)
SOURCE CODE
% Data representation of all informations related to one subject
%   Contains:
%           a name,
%           edaValues,
%           hrvValues,
%           eegValuesForElectrodes,
%           validElectrodes,
%           isValid,
%           edaPerVid,
%   hence, two different constructors are necessary
%   See: SubjectFactory, DataFactory
%
% Author: Gernot Heisenberg
%
classdef Subject
    properties
        %Initial values set during creation in SubjectFactory
        name = ''
        % parsed eda values
        edaValues={}
        % parsed hrv values
        hrvValues={}
        % parsed eeg values and status of position
        eegValuesForElectrodes ={}
        validElectrodes = []
        %Values set during FilterAction
        isValid = 1
        edaPerVid= {}
    end
    methods
        function eegValues = eegValuesByElectrode(self, electrode)
            eegValues = {};
            numEegValues = length(self.eegValuesForElectrodes);
            for i=1:numEegValues
                currentElectrode = self.eegValuesForElectrodes{i}.electrode;
                if (electrode == currentElectrode)
                    eegValues = self.eegValuesForElectrodes{i};
                end
            end
        end
    end
end