Description of VideoDefinition
VideoDefinition
PURPOSE
Data representation of a VideoDefinition.
SYNOPSIS
This is a script file.
DESCRIPTION
Data representation of a VideoDefinition.
   Stores one row of the video definition file.
CROSS-REFERENCE INFORMATION
This function calls:
VideoDefinition Data representation of a VideoDefinition.
This function is called by:
DataFactory Factory class creating _Data_ objects
VideoDefinition Data representation of a VideoDefinition.
SUBFUNCTIONS
function VD = VideoDefinition(type,l,intervals)
SOURCE CODE
%Data representation of a VideoDefinition.
%   Stores one row of the video definition file.
classdef VideoDefinition
    properties
        videoType % See: VideoType
        length % Length of the Video
        intervals ={} % Intervals of interest
    end
    methods
        %% Constructor: Creates new VideoDefinition and sets values
        function VD = VideoDefinition(type,l,intervals)
            VD.videoType = type;
            VD.length = l;
            VD.intervals = intervals;
        end
    end
end